services:
  - type: web
    name: resp
    env: static
    buildCommand: npm install && npm run build && cp dist/index.html dist/200.html && cp dist/index.html dist/404.html
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: build
    envVars:
      - key: VITE_API_URL
        value: https://api.appinovavoip.com
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
      - key: VITE_SUPABASE_URL
        value: https://cnollcnzgamecikeoymj.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNub2xsY256Z2FtZWNpa2VveW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1ODk3NzksImV4cCI6MjA1MTE2NTc3OX0.XBzhypt2ZGiYbQKL3HEFZyhTEhjj4c1iJf6uCAPQOEg
    routes:
      - type: rewrite
        source: /api/*
        destination: https://api.appinovavoip.com/:splat
      - type: rewrite
        source: /rest/v1/*
        destination: https://cnollcnzgamecikeoymj.supabase.co/rest/v1/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
      - path: /*
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: Referrer-Policy
        value: "strict-origin-when-cross-origin"
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains"
