services:
  - type: web
    name: sistemacompletoinova
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: master
    envVars:
      - key: VITE_API_URL
        value: https://91.108.125.149:5000
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
    routes:
      - type: rewrite
        source: /api/*
        destination: https://91.108.125.149:5000/:splat
      - type: rewrite
        source: /static/*
        destination: /static/:splat
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate, proxy-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0
      - path: /*
        name: Surrogate-Control
        value: no-store
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
