services:
  - type: web
    name: sistemacompletoinova
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: master
    envVars:
      - key: VITE_API_URL
        value: https://91.108.125.149:5000
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
