services:
  - type: web
    name: resp
    env: static
    buildCommand: npm install && npm run build && cp dist/index.html dist/200.html && cp dist/index.html dist/404.html
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://api.appinovavoip.com
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
    routes:
      - type: rewrite
        source: /api/*
        destination: https://api.appinovavoip.com/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
