services:
  - type: static
    name: sistemacompletoinova
    buildCommand: npm install && npm run build
    publishDir: dist
    staticPublishPath: /
    autoDeploy: true
    branch: master
    envVars:
      - key: VITE_API_URL
        value: http://91.108.125.149:5000
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
