services:
  - type: web
    name: sistemacompletoinova
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    branch: master
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
    envVars:
      - key: VITE_API_URL
        value: http://91.108.125.149:5000
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
