services:
  - type: web
    name: sistemacompletoinova
    env: static
    buildCommand: npm install && npm run build && cp dist/index.html dist/404.html
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    branch: master
    envVars:
      - key: VITE_API_URL
        value: https://91.108.125.149:5000
      - key: VITE_SECRET_KEY
        value: inovavoip-secure-key-2024
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
